### DISCUSSION TITLE
Callout Symbols

### DISCUSSION THREAD

**Discussion by hngan943** [efemkay/obsidian-modular-css-layout#44] [Q&A]
Hi, I wonder how you can modify your callout symbols to the right like this image
![mc-callout-standard](https://github.com/efemkay/obsidian-modular-css-layout/assets/140294108/a1d10092-5137-4981-aec1-598199531273)
Mine looks like this and I dont know how to change
![image](https://github.com/efemkay/obsidian-modular-css-layout/assets/140294108/89915b52-509b-429b-aa6c-3cb118866c07)

**Comment by efemkay** [comment]
That's my theme (Listive) customisation. I can share later, not at pc right now.

I guess that can be confusing for relatively new users. Need to either standardise my screenshots somehow or put a note on the theme I use for the screenshot

MCL won't do these kind of customisation (i.e. color scheme, prettifying like font or icon). It will provide layout. If there's any minor customisation, it will use obsidian default variables so that it will be up to theme.

**Comment by efemkay** [comment]
here's the css snippet for the callout icon placement

> if you need help on how to create and place snippets, follow link below
> - https://help.obsidian.md/Extending+Obsidian/CSS+snippets
> - https://forum.obsidian.md/t/obsidian-css-quick-guide/58178

```css
/* Default style: "callout-style-icon-right" i.e. icon on the top right */
body .callout {
    position: relative;
}
body .callout > .callout-title > .callout-icon {
    --icon-size: 48px;
    opacity: 0.3;
    position: absolute;
    top: -10px;
    right: -8px;
}
```

![image](https://github.com/efemkay/obsidian-modular-css-layout/assets/42369515/0a1e67f9-80e3-42fb-abe7-2f304cb31f2b)
