### DISCUSSION TITLE
Source of callout symbols/icons?

### DISCUSSION THREAD

**Discussion by hopezh** [efemkay/obsidian-modular-css-layout#99] [Q&A]
May I ask the source of the callout symbols/icons where I can find their name to add in the `VAULT_NAME/.obsidian/snippets/callout.css`, as shown below?

```css
.callout[data-callout="fingerprint"] {
    --callout-color: 255, 255, 0;
    --callout-icon: lucide-fingerprint;
}
```

<img width="958" alt="Screenshot 2024-08-10 at 10 19 16 PM" src="https://github.com/user-attachments/assets/c3b24f51-171f-454e-b7ca-5d274bb42c80">
