### ISSUE TITLE
MCL Wide Views not working with DataviewJS

### ISSUE THREAD

**Issue by ZobaJakColbert** [efemkay/obsidian-modular-css-layout#96]
I think wide views for dataviewjs is broken right now.

On top table with dataviewjs, on bottom the same table but done with dataview.
![350678435-4a6c3f80-fcaa-4d7a-b44e-984833b29248](https://github.com/user-attachments/assets/b4ebca06-f52c-42d7-9895-d52d24632229)

**Comment by efemkay** [comment]
hi there. yup, i can see the wide-table is broken for dataviewjs on my end as well. tqs

**Comment by harrislop** [comment]
Has this part not been resolved yet..?

**Comment by ZobaJakColbert** [comment]
Still unresolved.

**Comment by harrislop** [comment]
> Still unresolved.

It's sad. I'm using it with a tracker, but it appears too small, and that makes me feel sad.

**Comment by elvarb** [comment]
I'm using DataviewJS with the Chronos Timeline plugin and using wide-dataview works on both standard dataview and dataviewjs block with chronos

**Comment by ZobaJakColbert** [comment]
I installed Chronos Timeline plugin and no change in displaying occured. Same width as in my screenshot.

**Comment by elvarb** [comment]
Could it be that the theme you are using is overwriting the custom css ?

I'm using this one https://github.com/LostViking09/obsidian-fastppuccin

**Comment by ZobaJakColbert** [comment]
No, I'm using default theme.

Now I created new vault, installed Dataview (enabled DataviewJS), Chronos Timeline and fastppuccin. And it's also not working - dataview is wide, dataviewjs table is narrow.

When you uncheck Readable line length it is working as should, but it should work with Readable line length on.

![Image](https://github.com/user-attachments/assets/6cb691a4-3870-4e16-9d50-33c5eb0cb9ec)

**Comment by ZobaJakColbert** [comment]
Ok, I changed in `MCL Wide Views.css` this code from line 103 and now it's working: 

```css
        /* reading view - only node-insert-event divs that contain table */
        :is(.wide-table-global .markdown-preview-view, .wide-table.markdown-preview-view)
        div.node-insert-event:has(> table, > div > table) {
            width: 100cqi;
            margin-left: calc(
                max(100cqi - var(--file-line-width), 1rem) / 2 * -1
            ) !important;
        }
```
